### ISSUE TITLE
Push out new release of Cake.Jira

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Jira#11]
@Ninglin @joaopgmaria @carlos-vicente are we in a position to push out a new release of Cake.Jira?  Looks like there were some changes to update to the recommended version of Cake, which haven't made it out to NuGet.

**Comment by Ninglin** [comment]
@gep13 I'm not able to do it right now. Next week I'll find some time do release it.

**Comment by gep13** [comment]
That is great news! Thanks for letting me know!

**Comment by Ninglin** [comment]
@gep13 seems I'm not able to start a new deployment on app veyor. Maybe something to do with permissions?

**Comment by Ninglin** [comment]
I know the publish to nuget should be in the pipeline but I never got around to doing it. I'll implement it at a later time. For now a appveyor deployment would suffice to get this closed.

**Comment by gep13** [comment]
@Ninglin deployments in AppVeyor isn't something actually I have really used before, and as a result, not a permission that is typically added to the Roles that are created in AppVeyor.

I have just added the permission to "Deploy to Environment" for your Role on the Cake.Jira project.

Can you let me know if this is all that is required?  If not, I can look into adding more permissions for you.

**Comment by Ninglin** [comment]
Hi @gep13. I think I need to be able to create an environment also.

**Comment by gep13** [comment]
@Ninglin sorry, just seeing this now.  Looks like there already was an environment set up, so I have included the Cake.Jira project in this environment, and given you permissions to publish a deployment.  Can you let me know if you can do what you need to do?  Thanks

**Comment by Ninglin** [comment]
@gep13 Version is released. Should be listed 0.7.0. Closing this

**Comment by gep13** [comment]
@Ninglin thank you very much!  Really appreciate it!
