### ISSUE TITLE
Move this repository to Cake-Contrib

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Jira#7]
@Ninglin thank you for inviting me to collaborate on this repository, however, in order to be able to move it into the Cake-Contrib Organisation, I would need you to transfer the repository to my GitHub User, not simply invite me to collaborate.

This can be done in the Settings for the repository here:

![image](https://user-images.githubusercontent.com/1271146/49539649-0ec7fa80-f8c6-11e8-98e9-b27f0b792ac3.png)

Let me know if you have any questions.

**Comment by gep13** [comment]
@Ninglin just wanted to touch base again on this to see if this is something that you wanted to continue with.

Thanks.  Let me know if you have any questions.

**Comment by Ninglin** [comment]
@gep13 I'm currently able to maintain this. Should I come to a time where I'm not able to maintain this I'll certainly transfer the repo's ownership to you guys

**Comment by gep13** [comment]
@Ninglin thanks for getting back to me!

Moving a repository into the Cake-Contrib Organisation isn't about taking maintenance of the addin away from you,  quite it opposite!  You would be invited into the Cake-Contrib Organisation and given the exact same access to the repository as you have now, it is just that the repository would live under a different location, and you would be encouraged to continue maintenance the same way as you are just now.

Let me try to explain further why this request was made...

We have had an incident in the past where a maintainer of an addin repository sadly died.  When people tried to get access to the repository to continue the development effort we were unable to get access to the repo.  The end result was that we forked the repo into the Cake-Contrib Organisation and continued development.  This isn't perfect, but it does work, it just means that there is potentially slight confusion about which repo is the "current" one.  The most important thing was getting access to push the package to nuget.org under the same ID, so that this also didn't cause confusion..  At the time, we didn't have the cake-contrib user on NuGet, which we do now, and Cake.Jira has this user as a maintainer of the package, however, we were able to be added to the package retrospectively by the NuGet Team.  They have made it clear that this is unlikely to happen again though.  That is why we encourage people to add the cake-contrib user immediately to any addin package, and when willing, also move the repository under the Cake-Contrib GitHub Organisation.  

This means that in the event of something serious, everything is in place to continue development of the addin.  However, this would only happen if something were to occur.  Otherwise, you would see no change to how you are currently doing things.

Does all of that make sense?  Please let me know if you have any further questions.

**Comment by gep13** [comment]
@Ninglin just wanted to follow up with this again, to see if you had any follow up questions/concerns.  Thanks

**Comment by Ninglin** [comment]
Hi @gep13, I'm not comfortable with giving away the repository ownershipo just noww. Maybe in the future I will pass it on to you, but for now I'd like to keep in under me.

**Comment by gep13** [comment]
@Ninglin I have a genuine question to ask, as I would love to understand... 

What exactly is it that you are not comfortable with?  

If the transfer were to go ahead, you would have the same permissions on the repository as you currently have, i.e. full control, it would just live under the Cake-Contrib Organisation.

**Comment by Ninglin** [comment]
I'll transfer it. Was just having problems letting the baby go.

**Comment by Ninglin** [comment]
@gep13 You'll need to give me the proper permissions on the org.

**Comment by gep13** [comment]
@Ninglin This is great news, and I totally understand where you are coming from with "letting the baby go", however, hopefully once transferred, it will be clear that you still have the same rights as you do now.

In order to allow you, as an individual to transfer directly into the Cake-Contrib Organisation, I would need to make you an overall owner of the Organisation, rather than a single repository in the Organisation.  This isn't something that we typically do, but rather, we normally have an initial transfer to someone who is an owner of the Organisation (i.e. myself or someone else in the Cake Team) and then a secondary transfer is done immediately to the Cake-Contrib Organisation.

Does that make sense?

If so, if you can transfer the repo to me, I will get it immediately moved into the Organisation.

I have just sent you an invite to join the Cake-Contrib Organisation, and once the repository transfer is complete, I will immediately add you with Admin permissions to the Cake.Jira repository.

Please let me know if you have any questions.

**Comment by Ninglin** [comment]
It's okay. I'll transfer it to you now.

**Comment by gep13** [comment]
@Ninglin I have now completed the transfer:

https://github.com/cake-contrib/Cake.Jira

And you should have full admin permissions to the repository.

I notice that there are two other collaborators on the repository.  Would you like for me to invite them to the Cake-Contrib Organisation as well?

Do you have a twitter account, and do you use Slack?  If so, could you let me know details for both of these, and I will follow your Twitter account from the cake-contrib Twitter account, and I can invite you to a Slack Team for Cake Addin maintainers.

**Comment by gep13** [comment]
@Ninglin Thanks again for doing this, I really appreciate it!

**Comment by Ninglin** [comment]
Nice, You should also invite the other maintainers to the org and give them admin on the repo.

**Comment by Ninglin** [comment]
they are @joaopgmaria and @carlos-vicente

**Comment by gep13** [comment]
I have just invited them to the Organisation, and given them Admin access to the repository.

The same request for Twitter and Slack information exists for them, so that I can add them to those as well.

Thanks

**Comment by gep13** [comment]
@Ninglin I have also created a new AppVeyor Build for this repository under the Cake-Contrib Account on AppVeyor, and I am currently syncing permissions between GitHub and AppVeyor, so that each person has access to the project there:

https://ci.appveyor.com/project/cakecontrib/cake-jira

**Comment by Ninglin** [comment]
Thank you @gep13 . I didn't receive any request for twitter and Slack

**Comment by gep13** [comment]
@Ninglin I mentioned it in this comment here:

https://github.com/cake-contrib/Cake.Jira/issues/7#issuecomment-492278448

At the end 😄

**Comment by Ninglin** [comment]
Oh damn, missed that. My twitter is @hugomctavares and you can send the slack invite to hugo.tavares.9@gmail.com

**Comment by gep13** [comment]
This has now been completed.
